### ISSUE TITLE
[BE] 문서 최신화 - API 명세서

### ISSUE THREAD

**Issue by BE-02-KMJ** [OZ-Coding-School/oz_02_collabo-003-BE#126]

**Comment by BE-02-KMJ** [comment]
https://docs.google.com/spreadsheets/d/1LiE42upvHz_zoFitKVucrfBJrCZL1AaSS9UpHhzsTz8/edit?usp=sharing

API 명세서 ver.2 작성했습니다~
@joowhi 님 짜신 코드 부분 작성해주셔서 감사합니당 ㅎㅎㅎ
@Hyunminmax 검토 부탁드려요~~

< 메인 페이지 API 명세서 >
![image](https://github.com/OZ-Coding-School/oz_02_collabo-003-BE/assets/155046238/9e38d0a0-1a7d-4ec4-aeba-2ef517ce44f1)

< 관리자 페이지 API 명세서 >
![image](https://github.com/OZ-Coding-School/oz_02_collabo-003-BE/assets/155046238/69976657-aafb-4dc9-90f4-2cf095814c39)
![image](https://github.com/OZ-Coding-School/oz_02_collabo-003-BE/assets/155046238/066c8f6c-734c-4afd-99bb-307179eabade)
![image](https://github.com/OZ-Coding-School/oz_02_collabo-003-BE/assets/155046238/a6e2a774-301c-40ea-bd41-c1ae5367f4cd)
![image](https://github.com/OZ-Coding-School/oz_02_collabo-003-BE/assets/155046238/ad24772d-45c0-4820-823e-29ec78991450)

**Comment by Hyunminmax** [comment]
네! 진행들어갑니다.
