### ISSUE TITLE
[BE] 문서 최신화 - 테이블 명세서

### ISSUE THREAD

**Issue by BE-02-KMJ** [OZ-Coding-School/oz_02_collabo-003-BE#127]

**Comment by BE-02-KMJ** [comment]
https://docs.google.com/spreadsheets/d/1zbsPnc3SjtipwWBq3yKuFAkQGqJYCWKeZno1zLyg99E/edit?gid=1607254008#gid=1607254008

테이블 명세서 ver.2 작성했습니다~ 확인 부탁드려요 ㅎㅎ
@Hyunminmax @joowhi 

< 테이블 명세서 >
![image](https://github.com/OZ-Coding-School/oz_02_collabo-003-BE/assets/155046238/2c73abc1-a943-42ab-ad18-96c5e3096d4a)

< 우측 속성 예시 표 >
![image](https://github.com/OZ-Coding-School/oz_02_collabo-003-BE/assets/155046238/ce64d41d-f21f-486d-b7eb-2e42cdb8596f)

**Comment by Hyunminmax** [comment]
admins_kluck_admin 테이블의 admin_id >> cell_num 으로 정정
